// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALqP8PmyLskXn8nbbFSd6LWI33vviSekM',
    appId: '1:634549873296:web:0bfcf080c2027ef2e34615',
    messagingSenderId: '634549873296',
    projectId: 'mrsneakers-996f3',
    authDomain: 'mrsneakers-996f3.firebaseapp.com',
    storageBucket: 'mrsneakers-996f3.firebasestorage.app',
    measurementId: 'G-YNWVS2KDX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcsofHLBtTj0pnLA5Wr7qTX2NMwdKAWOk',
    appId: '1:634549873296:android:4ca60132b5ab48bbe34615',
    messagingSenderId: '634549873296',
    projectId: 'mrsneakers-996f3',
    storageBucket: 'mrsneakers-996f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-N57xHFxccCaYmHcTdihyIv00kn8a_Kg',
    appId: '1:634549873296:ios:695ee47223ed5b36e34615',
    messagingSenderId: '634549873296',
    projectId: 'mrsneakers-996f3',
    storageBucket: 'mrsneakers-996f3.firebasestorage.app',
    iosBundleId: 'com.example.mrsneakersapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-N57xHFxccCaYmHcTdihyIv00kn8a_Kg',
    appId: '1:634549873296:ios:695ee47223ed5b36e34615',
    messagingSenderId: '634549873296',
    projectId: 'mrsneakers-996f3',
    storageBucket: 'mrsneakers-996f3.firebasestorage.app',
    iosBundleId: 'com.example.mrsneakersapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALqP8PmyLskXn8nbbFSd6LWI33vviSekM',
    appId: '1:634549873296:web:137b66bdf54a09d3e34615',
    messagingSenderId: '634549873296',
    projectId: 'mrsneakers-996f3',
    authDomain: 'mrsneakers-996f3.firebaseapp.com',
    storageBucket: 'mrsneakers-996f3.firebasestorage.app',
    measurementId: 'G-T99KZXWP8N',
  );
}
